openapi: 3.0.1
info:
  title: Moldova Fuel Station API
  description: Description of available APIs for interacting with fuel stations in Moldova.
  version: v1
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Fuel Station Controller
    description: A group of controllers to work with fuel station data.
paths:
  /page/fuel-station:
    get:
      tags:
        - Fuel Station Controller
      summary: Get page of all fuel stations within a certain radius.
      description: Returns all fuel stations within a certain radius in page format.
      operationId: getPageOfAllFuelStations
      parameters:
        - name: latitude
          in: query
          description: Latitude of the starting point of the search.
          required: true
          schema:
            maximum: 90
            exclusiveMaximum: false
            minimum: -90
            exclusiveMinimum: false
            type: number
            format: double
          example: 46
        - name: longitude
          in: query
          description: Longitude of the starting point of the search.
          required: true
          schema:
            maximum: 90
            exclusiveMaximum: false
            minimum: -90
            exclusiveMinimum: false
            type: number
            format: double
          example: 28
        - name: radius
          in: query
          description: Search radius for petrol stations in metres.
          required: true
          schema:
            minimum: 0
            exclusiveMinimum: false
            type: number
            format: double
          example: 5000
        - name: limit_in_radius
          in: query
          description: Number of fuel stations allowed to be displayed within a certain radius.
          required: true
          schema:
            minimum: 1
            type: integer
            format: int32
          example: 10
        - name: limit
          in: query
          description: Limit of one page of returned results.
          required: true
          schema:
            minimum: 0
            type: integer
            format: int32
          example: 20
        - name: offset
          in: query
          description: The number of items skipped from the beginning of the list.
          required: true
          schema:
            minimum: 0
            type: integer
            format: int32
          example: 0
      responses:
        '200':
          description: OK.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageDtoFuelStationDto'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
  /page/fuel-station/{fuel-type}:
    get:
      tags:
        - Fuel Station Controller
      summary: Get page of fuel stations with the best specified fuel type within a certain radius.
      description: Return fuel stations with the best specified fuel type within a certain radius in page format.
      operationId: getPageOfBestFuelPrice
      parameters:
        - name: latitude
          in: query
          description: Latitude of the starting point of the search.
          required: true
          schema:
            maximum: 90
            exclusiveMaximum: false
            minimum: -90
            exclusiveMinimum: false
            type: number
            format: double
          example: 46
        - name: longitude
          in: query
          description: Longitude of the starting point of the search.
          required: true
          schema:
            maximum: 90
            exclusiveMaximum: false
            minimum: -90
            exclusiveMinimum: false
            type: number
            format: double
          example: 28
        - name: radius
          in: query
          description: Search radius for petrol stations in metres.
          required: true
          schema:
            minimum: 0
            exclusiveMinimum: false
            type: number
            format: double
          example: 5000
        - name: limit_in_radius
          in: query
          description: Number of fuel stations allowed to be displayed within a certain radius.
          required: true
          schema:
            minimum: 1
            type: integer
            format: int32
          example: 10
        - name: limit
          in: query
          description: Limit of one page of returned results.
          required: true
          schema:
            minimum: 0
            type: integer
            format: int32
          example: 20
        - name: offset
          in: query
          description: The number of items skipped from the beginning of the list.
          required: true
          schema:
            minimum: 0
            type: integer
            format: int32
          example: 0
        - name: fuel-type
          in: path
          description: Type of fuel for price search.
          required: true
          schema:
            type: string
            enum:
              - Petrol
              - Diesel
              - Gas
      responses:
        '200':
          description: OK.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageDtoFuelStationDto'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
  /fuel-station:
    get:
      tags:
        - Fuel Station Controller
      summary: Get all fuel stations in specific radius.
      description: Returns all fuel stations within a certain radius.
      operationId: getAllFuelStations
      parameters:
        - name: latitude
          in: query
          description: Latitude of the starting point of the search.
          required: true
          schema:
            maximum: 90
            exclusiveMaximum: false
            minimum: -90
            exclusiveMinimum: false
            type: number
            format: double
          example: 46
        - name: longitude
          in: query
          description: Longitude of the starting point of the search.
          required: true
          schema:
            maximum: 90
            exclusiveMaximum: false
            minimum: -90
            exclusiveMinimum: false
            type: number
            format: double
          example: 28
        - name: radius
          in: query
          description: Search radius for petrol stations in metres.
          required: true
          schema:
            minimum: 0
            exclusiveMinimum: false
            type: number
            format: double
          example: 5000
        - name: limit_in_radius
          in: query
          description: Number of fuel stations allowed to be displayed within a certain radius.
          required: true
          schema:
            minimum: 1
            type: integer
            format: int32
          example: 10
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FuelStationDto'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
  /fuel-station/{fuel-type}:
    get:
      tags:
        - Fuel Station Controller
      summary: Get fuel stations with the best specified fuel type within a certain radius.
      description: Return fuel stations with the best specified fuel type within a certain radius.
      operationId: getBestFuelPrice
      parameters:
        - name: latitude
          in: query
          description: Latitude of the starting point of the search.
          required: true
          schema:
            maximum: 90
            exclusiveMaximum: false
            minimum: -90
            exclusiveMinimum: false
            type: number
            format: double
          example: 46
        - name: longitude
          in: query
          description: Longitude of the starting point of the search.
          required: true
          schema:
            maximum: 90
            exclusiveMaximum: false
            minimum: -90
            exclusiveMinimum: false
            type: number
            format: double
          example: 28
        - name: radius
          in: query
          description: Search radius for petrol stations in metres.
          required: true
          schema:
            minimum: 0
            exclusiveMinimum: false
            type: number
            format: double
          example: 5000
        - name: limit_in_radius
          in: query
          description: Number of fuel stations allowed to be displayed within a certain radius.
          required: true
          schema:
            minimum: 1
            type: integer
            format: int32
          example: 10
        - name: fuel-type
          in: path
          description: Type of fuel for price search.
          required: true
          schema:
            type: string
            enum:
              - Petrol
              - Diesel
              - Gas
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FuelStationDto'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
  /fuel-station/nearest:
    get:
      tags:
        - Fuel Station Controller
      summary: Get nearest fuel station within a certain radius.
      description: Returns nearest fuel station within a certain radius.
      operationId: getNearestFuelStation
      parameters:
        - name: latitude
          in: query
          description: Latitude of the starting point of the search.
          required: true
          schema:
            maximum: 90
            exclusiveMaximum: false
            minimum: -90
            exclusiveMinimum: false
            type: number
            format: double
          example: 46
        - name: longitude
          in: query
          description: Longitude of the starting point of the search.
          required: true
          schema:
            maximum: 90
            exclusiveMaximum: false
            minimum: -90
            exclusiveMinimum: false
            type: number
            format: double
          example: 28
        - name: radius
          in: query
          description: Search radius for petrol stations in metres.
          required: true
          schema:
            minimum: 0
            exclusiveMinimum: false
            type: number
            format: double
          example: 5000
        - name: limit_in_radius
          in: query
          description: Number of fuel stations allowed to be displayed within a certain radius.
          required: true
          schema:
            minimum: 1
            type: integer
            format: int32
          example: 10
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FuelStationDto'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GatewayErrorDescription'
                  - $ref: '#/components/schemas/RfcErrorDescription'
components:
  schemas:
    Errors:
      required:
        - Error
      type: object
      properties:
        Error:
          type: array
          description: List of gateway errors.
          items:
            $ref: '#/components/schemas/GatewayError'
      description: Errors list wrapper.
    GatewayError:
      required:
        - description
        - reasonCode
        - recoverable
        - source
      type: object
      properties:
        source:
          type: string
          description: Error source.
          example: MD_FUEL_APP
        reasonCode:
          type: string
          description: Error reason code.
          example: NOT_FOUND
        description:
          type: string
          description: Error description.
          example: Not Found.
        recoverable:
          type: boolean
          description: Error recoverable status.
          example: true
      description: Gateway error.
    GatewayErrorDescription:
      type: object
      properties:
        Errors:
          $ref: '#/components/schemas/Errors'
      description: Gateway error list wrapper.
    RfcError:
      required:
        - message
        - reason
        - recoverable
        - source
      type: object
      properties:
        source:
          type: string
          description: Error source.
          example: MD_FUEL_APP
        reason:
          type: string
          description: Error reason code.
          example: NOT_FOUND
        message:
          type: string
          description: Error description.
          example: Not Found.
        recoverable:
          type: boolean
          description: Error recoverable status.
          example: true
      description: Error in RFC format.
    RfcErrorDescription:
      required:
        - detail
        - status
        - title
      type: object
      properties:
        status:
          type: integer
          description: Error status.
          format: int32
          example: 404
        detail:
          type: string
          description: Error description.
          example: Not Found.
        title:
          type: string
          description: Error reason code.
          example: NOT_FOUND
        type:
          type: string
          description: Error type.
          example: Error type.
        correlationId:
          type: string
          description: Correlation id.
          example: Correlation id
        errorDetails:
          type: array
          description: List of errors in RFC format.
          items:
            $ref: '#/components/schemas/RfcError'
      description: RFC Errors wrapper.
    FuelStationDto:
      required:
        - diesel
        - gas
        - latitude
        - longitude
        - name
        - petrol
      type: object
      properties:
        name:
          type: string
          description: Fuel Station Name.
          example: Fuel-Station
        petrol:
          type: number
          description: Petrol price.
          format: double
          example: 10
        diesel:
          type: number
          description: Diesel price.
          format: double
          example: 15
        gas:
          type: number
          description: Gas price.
          format: double
          example: 20
        latitude:
          type: number
          description: Fuel station latitude.
          format: double
          example: 46
        longitude:
          type: number
          description: Fuel station longitude.
          format: double
          example: 28
    PageDtoFuelStationDto:
      required:
        - items
        - totalResults
      type: object
      properties:
        totalResults:
          type: integer
          description: Total number of fuel stations in radius.
          format: int32
          example: 10
        items:
          type: array
          description: List of fuel stations.
          items:
            $ref: '#/components/schemas/FuelStationDto'
      description: Page with list of items and total results.