api-configuration:
  retry-count: 2
  time-duration: 500
  retryable: 429

  base-path: ${filling-station.api-host:http://localhost:8080}

  paths:
    all-filling-stations-page:
      path: /page/filling-station
      parameters: latitude, longitude, radius, limit_in_radius, sorting, limit, offset
    nearest:
      path: /filling-station/nearest
      parameters: latitude, longitude, radius
    best-fuel-price-page:
      path: /page/filling-station/{fuel-type}
      parameters: latitude, longitude, radius, limit_in_radius, sorting, limit, offset
    last-update:
      path: /filling-station/last-update
      parameters: ~
    fuel-type:
      path: /filling-station/fuel-type
      parameters: ~